id: IB5279785
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T16:56:39+00:00'
last_modified: '2022-06-15T16:25:34.893804+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23697
  title: རྟེན་འབྲེལ་ཟབ་མོའི་བརྗོད་བྱ་སྣ་ཚོགས་པ་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ་སྐལ་ལྡན་ཡིད་འཕྲོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C40B:
      image_group_id: I1KG23780
      title: Volume 1 of rten 'brel zab mo'i brjod bya sna tshogs pa phyogs gcig tu
        bsdebs pa skal ldan yid 'phrog
      total_pages: 270
      order: 1
      base_file: C40B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
